using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.XtraBars;
using System.ComponentModel.DataAnnotations;

namespace DMDS
{
    public partial class Form1 : DevExpress.XtraBars.Ribbon.RibbonForm
    {
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }
        void bbiPrintPreview_ItemClick(object sender, ItemClickEventArgs e)
        {
            //gridControl1.ShowRibbonPrintPreview();
        }
        
        private void Form1_Load(object sender, EventArgs e)
        {

        }

        private void gridControl1_DataSourceChanged(object sender, EventArgs e)
        {
            gridView1.OptionsBehavior.AutoPopulateColumns = false;
            gridView1.PopulateColumns();
            gridView1.BestFitColumns();
            bsiRecordsCount.Caption = "RECORDS : " + gridView1.RowCount;
            //checkedComboBoxEdit1.Name
        }

        #region Danh Sach Cac Bang

        private void barButtonItem11_ItemClick(object sender, ItemClickEventArgs e)
        {
            // TODO: This line of code loads data into the 'dSVDataSet.KHOA' table. You can move, or remove it, as needed.
            this.kHOATableAdapter.Fill(this.dSVDataSet.KHOA);
            gridControl1.DataSource = kHOABindingSource;
        }

        private void barButtonItem1_ItemClick(object sender, ItemClickEventArgs e)
        {
            // TODO: This line of code loads data into the 'dSVDataSet.GIANGVIEN' table. You can move, or remove it, as needed.
            this.gIANGVIENTableAdapter.Fill(this.dSVDataSet.GIANGVIEN);
            gridControl1.DataSource = gIANGVIENBindingSource;
        }

        private void barButtonItem2_ItemClick(object sender, ItemClickEventArgs e)
        {
            // TODO: This line of code loads data into the 'dSVDataSet.LOP' table. You can move, or remove it, as needed.
            this.lOPTableAdapter.Fill(this.dSVDataSet.LOP);
            gridControl1.DataSource = lOPBindingSource;
        }

        private void barButtonItem3_ItemClick(object sender, ItemClickEventArgs e)
        {
            // TODO: This line of code loads data into the 'dSVDataSet.SINHVIEN' table. You can move, or remove it, as needed.
            this.sINHVIENTableAdapter.Fill(this.dSVDataSet.SINHVIEN);
            gridControl1.DataSource = sINHVIENBindingSource;
        }

        private void barButtonItem4_ItemClick(object sender, ItemClickEventArgs e)
        {
            // TODO: This line of code loads data into the 'dSVDataSet.MONHOC' table. You can move, or remove it, as needed.
            this.mONHOCTableAdapter.Fill(this.dSVDataSet.MONHOC);
            gridControl1.DataSource = mONHOCBindingSource;
        }

        private void barButtonItem5_ItemClick(object sender, ItemClickEventArgs e)
        {
            // TODO: This line of code loads data into the 'dSVDataSet.DIEM' table. You can move, or remove it, as needed.
            this.dIEMTableAdapter.Fill(this.dSVDataSet.DIEM);
            gridControl1.DataSource = dIEMBindingSource;
        }

        #endregion

        #region Bao Cao Cac Bang

        #endregion

        private void barButtonItem6_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem7_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem8_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem9_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem10_ItemClick(object sender, ItemClickEventArgs e)
        {

        }

        private void barButtonItem12_ItemClick(object sender, ItemClickEventArgs e)
        {
        }

        private void bbiNew_ItemClick(object sender, ItemClickEventArgs e)
        {
            gridView1.AddNewRow();
        }

        private void bbiDelete_ItemClick(object sender, ItemClickEventArgs e)
        {
            gridView1.DeleteRow(gridView1.FocusedRowHandle);
        }

        private void bbiEdit_ItemClick(object sender, ItemClickEventArgs e)
        {
            
        }

        private void gridView1_InitNewRow(object sender, DevExpress.XtraGrid.Views.Grid.InitNewRowEventArgs e)
        {
            gridView1.SetRowCellValue(e.RowHandle, "rowguid", Guid.NewGuid());
        }

    }
}